// Aerix Liquid Crystal - screen definitions.
// One entry per dock tab; every option of the launcher is represented here.

const sec = (label, right, icon) => ({ t: 'section', label, right, icon });
const row = (icon, tint, title, sub, control, value) =>
  ({ t: 'row', icon, tint, title, sub, control, value });
const tile = (icon, tint, title, control) => ({ icon, tint, title, control });
const slider = (icon, tint, title, value, valueText, h = 100) =>
  ({ t: 'slider', icon, tint, title, value, valueText, h });
const gap = (h) => ({ t: 'gap', h });

export const TABS = [
  { name: 'LAUNCH', icon: 'rocket', tint: 'cyan' },
  { name: 'INSTANCE', icon: 'layers', tint: 'mint' },
  { name: 'MODS', icon: 'puzzle', tint: 'violet' },
  { name: 'CONTROL', icon: 'gamepad-2', tint: 'azure' },
  { name: 'SETTINGS', icon: 'sliders-horizontal', tint: 'cyan' },
  { name: 'VIDEO', icon: 'monitor-play', tint: 'rose' },
  { name: 'INPUT', icon: 'hand', tint: 'mint' },
  { name: 'JAVA', icon: 'coffee', tint: 'amber' },
  { name: 'MISC', icon: 'folder-cog', tint: 'cyan' },
  { name: 'LABS', icon: 'flask-conical', tint: 'violet' },
];

export const SCREENS = [
  // ------------------------------------------------------------------ 01
  {
    kicker: 'AERIX', title: 'Ready when you are', subtitle: 'Aerix Liquid Crystal',
    actions: [
      { icon: 'bell', tint: 'white' },
      { icon: 'user-round', tint: 'cyan', glow: true },
    ],
    blocks: [
      { t: 'custom', id: 'hero', h: 220 },
      gap(28),
      { t: 'custom', id: 'console', h: 452 },
      gap(30),
      sec('QUICK ACTIONS', '6 actions'),
      { t: 'tiles', cols: 3, h: 108, items: [
        tile('gamepad-2', 'azure', 'Custom controls'),
        tile('package', 'amber', 'Execute a .jar'),
        tile('share-2', 'cyan', 'Share log file'),
      ] },
      gap(12),
      { t: 'tiles', cols: 3, h: 108, items: [
        tile('folder-open', 'mint', 'Game directory'),
        tile('book-open', 'violet', 'Wiki & news'),
        tile('users', 'rose', 'Community'),
      ] },
      gap(30),
      sec('ACTIVE TASKS', '2 running'),
      { t: 'custom', id: 'tasks', h: 190 },
      gap(30),
      sec('ACCOUNT', 'switch'),
      row('user-round', 'cyan', 'Notch', 'Microsoft account · signed in', 'toggle_on'),
      gap(12),
      row('user', 'violet', 'Steve', 'Offline (local) account', 'chevron'),
      gap(18),
      { t: 'custom', id: 'addaccount', h: 96 },
    ],
  },
  // ------------------------------------------------------------------ 02
  {
    kicker: 'LIBRARY', title: 'Instances', subtitle: '4 instances · 24.8 GB used',
    actions: [
      { icon: 'search', tint: 'white' },
      { icon: 'plus', tint: 'mint', glow: true },
    ],
    blocks: [
      { t: 'search', placeholder: 'Search instances' },
      gap(18),
      { t: 'segmented', items: ['Release', 'Snapshot', 'Old-alpha', 'Old-beta'], active: 0, h: 72 },
      gap(28),
      sec('INSTALLED', 'edit'),
      { t: 'custom', id: 'instancecard', h: 122, data: {
        name: 'Aerix Survival', sub: '1.21.4 · Fabric 0.16.9 · 18 mods', icon: 'box',
        tint: 'mint', size: '12.4 GB', active: true } },
      gap(12),
      { t: 'custom', id: 'instancecard', h: 122, data: {
        name: 'Vanilla Plus', sub: '1.20.6 · Vanilla · 0 mods', icon: 'layers',
        tint: 'cyan', size: '3.1 GB' } },
      gap(12),
      { t: 'custom', id: 'instancecard', h: 122, data: {
        name: 'Beta Adventures', sub: 'b1.7.3 · Legacy Fabric', icon: 'package',
        tint: 'azure', size: '1.8 GB' } },
      gap(12),
      { t: 'custom', id: 'instancecard', h: 122, data: {
        name: 'NeoForge Lab', sub: '1.21.1 · NeoForge 21.1.72 · 42 mods',
        icon: 'flask-conical', tint: 'violet', size: '7.5 GB' } },
      gap(18),
      sec('INSTANCE EDITOR', 'Aerix Survival'),
      { t: 'custom', id: 'editor', h: 700 },
    ],
  },
  // ------------------------------------------------------------------ 03
  {
    kicker: 'DISCOVER', title: 'Mods & packs', subtitle: 'Install loaders, browse mods',
    actions: [
      { icon: 'download', tint: 'mint', glow: true },
      { icon: 'search', tint: 'white' },
    ],
    blocks: [
      { t: 'search', placeholder: 'Search mods and modpacks' },
      gap(26),
      sec('NEW INSTANCE', '9 types'),
      { t: 'tiles', cols: 3, h: 104, items: [
        tile('layers', 'mint', 'Vanilla'), tile('eye', 'cyan', 'OptiFine'),
        tile('puzzle', 'violet', 'Fabric'), tile('boxes', 'azure', 'Quilt'),
        tile('archive', 'rose', 'Legacy Fabric'), tile('flame', 'amber', 'Forge'),
        tile('box', 'lime', 'NeoForge'), tile('package', 'cyan', 'Modpack'),
        tile('hammer', 'violet', 'BTA'),
      ] },
      gap(28),
      sec('INSTALL FABRIC', 'step 2 of 2'),
      { t: 'custom', id: 'installer', h: 380 },
      gap(28),
      sec('BROWSE MODS', '1.2k results'),
      { t: 'custom', id: 'modcard', h: 118, data: {
        name: 'Sodium', sub: 'CaffeineMC · 24.6M downloads', ver: '1.21.4',
        size: '0.6.9', tint: 'mint' } },
      gap(12),
      { t: 'custom', id: 'modcard', h: 118, data: {
        name: 'Iris Shaders', sub: 'IrisDevs · 18.2M downloads', ver: '1.21.4',
        size: '1.8.0', tint: 'violet' } },
      gap(12),
      { t: 'custom', id: 'modcard', h: 118, data: {
        name: 'JEI', sub: 'mezz · 42.1M downloads', ver: '1.21.1',
        size: '19.21.0', tint: 'cyan' } },
      gap(20),
      { t: 'button', label: 'IMPORT LOCAL MODPACK', icon: 'file-archive', accent: false, h: 96 },
    ],
  },
  // ------------------------------------------------------------------ 04
  {
    kicker: 'DESIGN', title: 'Control studio', subtitle: 'Aerix default · 24 buttons',
    actions: [
      { icon: 'gamepad', tint: 'violet', glow: true },
      { icon: 'save', tint: 'mint' },
    ],
    blocks: [
      { t: 'custom', id: 'stage', h: 600 },
      gap(20),
      { t: 'custom', id: 'toolbar', h: 96 },
      gap(26),
      sec('BUTTON', 'KEY_JUMP'),
      row('keyboard', 'cyan', 'Mapping', '', 'value', 'KEY_SPACE'),
      gap(12),
      row('scaling', 'azure', 'Size', '', 'value', '96 × 96'),
      gap(12),
      row('palette', 'mint', 'Background', '', 'value', 'color'),
      gap(12),
      row('pipette', 'violet', 'Stroke', '', 'value', 'color'),
      gap(20),
      { t: 'tiles', cols: 2, h: 94, items: [
        tile('toggle-left', 'cyan', 'Toggleable', 'toggle_on'),
        tile('mouse-pointer-2', 'azure', 'Mouse pass-thru', 'toggle_off'),
      ] },
      gap(12),
      { t: 'tiles', cols: 2, h: 94, items: [
        tile('move', 'violet', 'Swipeable', 'toggle_off'),
        tile('lock', 'rose', 'Forward lock', 'toggle_off'),
      ] },
      gap(12),
      { t: 'tiles', cols: 1, h: 94, items: [
        tile('crosshair', 'mint', 'Absolute finger tracking', 'toggle_on'),
      ] },
      gap(20),
      slider('scan', 'cyan', 'Corner radius', 0.5, '50% · 48 dp'),
      gap(12),
      slider('ruler', 'azure', 'Stroke width', 0.3, '3 dp'),
      gap(12),
      slider('droplet', 'mint', 'Button opacity', 0.85, '85%'),
    ],
  },
  // ------------------------------------------------------------------ 05
  {
    kicker: 'CONTROL ROOM', title: 'Settings', subtitle: 'Everything in one control room',
    actions: [
      { icon: 'search', tint: 'white' },
      { icon: 'rotate-ccw', tint: 'mint' },
    ],
    blocks: [
      sec('CATEGORIES', '5'),
      { t: 'custom', id: 'categories', h: 782 },
      gap(26),
      sec('GENERAL', 'restart may apply'),
      row('languages', 'cyan', 'Force language to English',
          'See original strings, as intended by developers', 'toggle_off'),
      gap(12),
      row('bell', 'amber', 'Ask for notification permission',
          'Needed for download progress notifications', 'chevron'),
      gap(12),
      row('info', 'mint', 'About Aerix', 'Version 3.0 · Liquid Crystal', 'chevron'),
      gap(12),
      row('scroll-text', 'violet', 'Open source licenses',
          'Mesa, GL4ES, ANGLE, LWJGL and more', 'chevron'),
      gap(26),
      sec('SUPPORT', 'community'),
      row('book-open', 'azure', 'Wiki and news', '', 'chevron'),
      gap(12),
      row('users', 'rose', 'Community and socials', '', 'chevron'),
      gap(26),
      { t: 'note', icon: 'refresh-cw', tint: 'amber', h: 100,
        text: 'Changing the launcher language requires a full restart.' },
    ],
  },
  // ------------------------------------------------------------------ 06
  {
    kicker: 'PERFORMANCE', title: 'Video and renderer', subtitle: 'MobileGlues · 100% resolution',
    actions: [
      { icon: 'gauge', tint: 'rose', glow: true },
      { icon: 'rotate-ccw', tint: 'white' },
    ],
    blocks: [
      sec('RENDERER', '10 available'),
      { t: 'custom', id: 'renderers', h: 478 },
      gap(22),
      sec('PIPELINE', 'per instance'),
      row('sliders-horizontal', 'violet', 'Renderer settings', '', 'value',
          'OpenGL ES 3.2 · MSAA x2'),
      gap(12),
      slider('image', 'cyan', 'Resolution scaler', 1.0, '100% · 2400 × 1080'),
      gap(26),
      sec('DISPLAY AND POWER', 'battery aware'),
      { t: 'tiles', cols: 2, h: 94, items: [
        tile('smartphone', 'mint', 'Ignore notch', 'toggle_on'),
        tile('thermometer', 'amber', 'Sustained performance', 'toggle_off'),
      ] },
      gap(12),
      { t: 'tiles', cols: 2, h: 94, items: [
        tile('frame', 'azure', 'Alternate surface', 'toggle_off'),
        tile('activity', 'cyan', 'Force VSync', 'toggle_on'),
      ] },
      gap(26),
      sec('DRIVERS', 'advanced'),
      row('cpu', 'cyan', 'Use ANGLE', 'ANGLE instead of the system driver', 'toggle_on'),
      gap(12),
      row('server', 'azure', 'System ANGLE',
          'Use the ANGLE library shipped with the system', 'toggle_off'),
      gap(12),
      row('layers', 'violet', 'Zink prefer system driver',
          'Prefer the system Vulkan driver over Turnip', 'toggle_off'),
      gap(24),
      { t: 'note', icon: 'monitor-play', tint: 'rose', h: 96,
        text: 'Renderer changes apply the next time the game starts.' },
    ],
  },
  // ------------------------------------------------------------------ 07
  {
    kicker: 'TOUCH', title: 'Input and controls', subtitle: 'Gestures, mouse, gyro and gamepad',
    actions: [
      { icon: 'gamepad', tint: 'mint', glow: true },
      { icon: 'rotate-ccw', tint: 'white' },
    ],
    blocks: [
      sec('GESTURES', 'touch'),
      { t: 'tiles', cols: 2, h: 88, items: [
        tile('hand', 'azure', 'Disable gestures', 'toggle_off'),
        tile('mouse-pointer-click', 'cyan', 'Disable double tap', 'toggle_off'),
      ] },
      gap(10),
      slider('timer', 'cyan', 'Trigger long press delay', 0.42, '270 ms', 86),
      gap(20),
      sec('BUTTONS', 'on screen'),
      slider('scaling', 'azure', 'Control buttons scaling', 0.5, '100%', 86),
      gap(10),
      slider('droplet', 'violet', 'Button transparency', 1.0, '100%', 86),
      gap(10),
      { t: 'tiles', cols: 1, h: 88, items: [
        tile('type', 'amber', 'Uppercase button labels', 'toggle_off'),
      ] },
      gap(20),
      sec('VIRTUAL MOUSE', 'in game'),
      slider('mouse', 'mint', 'Mouse scaling', 0.5, '100% · 24 dp', 86),
      gap(10),
      slider('gauge', 'cyan', 'Mouse speed', 0.6, '100% · 1.0x', 86),
      gap(10),
      { t: 'tiles', cols: 1, h: 88, items: [
        tile('mouse-pointer-2', 'mint', 'Start with virtual mouse on', 'toggle_on'),
      ] },
      gap(20),
      sec('GYROSCOPE', 'sensor'),
      { t: 'tiles', cols: 2, h: 88, items: [
        tile('compass', 'cyan', 'Enable gyroscope', 'toggle_on'),
        tile('waves', 'azure', 'Gyroscope smoothing', 'toggle_off'),
      ] },
      gap(10),
      { t: 'tiles', cols: 2, h: 88, items: [
        tile('move-horizontal', 'violet', 'Invert X axis', 'toggle_off'),
        tile('move-vertical', 'violet', 'Invert Y axis', 'toggle_off'),
      ] },
      gap(10),
      slider('crosshair', 'cyan', 'Gyro sensitivity', 0.62, '100%', 86),
      gap(10),
      slider('activity', 'mint', 'Gyro sample rate', 0.4, '100 Hz', 86),
      gap(20),
      sec('CONTROLLER', 'physical'),
      row('gamepad', 'azure', 'Remap controller buttons', '', 'chevron'),
      gap(10),
      row('trash-2', 'rose', 'Wipe controller mappings', '', 'chevron'),
      gap(10),
      slider('circle-dot', 'violet', 'Controller deadzone', 0.3, '30%', 86),
      gap(20),
      sec('KEYBOARD', 'hardware'),
      { t: 'tiles', cols: 1, h: 88, items: [
        tile('keyboard', 'mint', 'Keyboard auto-panning', 'toggle_on'),
      ] },
    ],
  },
  // ------------------------------------------------------------------ 08
  {
    kicker: 'RUNTIME', title: 'Java tweaks', subtitle: 'JRE 21 · 4096 MB · sandbox on',
    actions: [
      { icon: 'plus', tint: 'amber', glow: true },
      { icon: 'search', tint: 'white' },
    ],
    blocks: [
      sec('RUNTIMES', '4 installed'),
      { t: 'custom', id: 'runtimes', h: 294 },
      gap(12),
      row('download', 'amber', 'Install a Java runtime',
          'Pick a version and download it from the runtime repository', 'chevron'),
      gap(26),
      sec('MEMORY', 'auto detected'),
      slider('memory-stick', 'cyan', 'Memory allocation', 0.62,
             '4096 MB · 52% of device memory'),
      gap(14),
      { t: 'note', icon: 'gauge', tint: 'cyan', h: 96,
        text: 'The launcher keeps 1.2 GB free for Android. Values above the limit are clamped at launch.' },
      gap(26),
      sec('ARGUMENTS', 'advanced'),
      row('terminal', 'violet', 'JVM launch arguments', '', 'value', 'custom'),
      gap(12),
      { t: 'custom', id: 'args', h: 96, data: {
        value: '-Xmx4096M -XX:+UseG1GC -XX:+ParallelRefProcEnabled' } },
      gap(26),
      sec('SECURITY', 'sandbox'),
      row('shield-check', 'mint', 'Sandbox .jar execution',
          'Controls the sandbox security manager for .jar files', 'toggle_on'),
      gap(14),
      { t: 'note', icon: 'lock', tint: 'mint', h: 96,
        text: 'Sandboxing stops executed .jar files from touching files outside of their own folder.' },
      gap(26),
      sec('RUNTIME INFO', 'device'),
      row('coffee', 'amber', 'Default runtime', '', 'value', 'JRE 21.0.3'),
      gap(12),
      row('folder-open', 'cyan', 'Runtime path', '', 'value', '/data/.../jre21'),
      gap(12),
      row('cpu', 'azure', 'Available memory', '', 'text', '7.8 GB free'),
    ],
  },
  // ------------------------------------------------------------------ 09
  {
    kicker: 'MAINTENANCE', title: 'Miscellaneous', subtitle: 'Integrity, downloads and storage',
    actions: [
      { icon: 'refresh-cw', tint: 'cyan', glow: true },
      { icon: 'search', tint: 'white' },
    ],
    blocks: [
      sec('INTEGRITY', 'launch time'),
      row('shield-check', 'mint', 'Verify game files',
          'Re-download broken or modified game libraries', 'chevron'),
      gap(12),
      row('zap', 'cyan', 'Fast startup check',
          'Skip the full integrity check when starting', 'toggle_on'),
      gap(12),
      row('file-check', 'azure', 'Verify manifest',
          'Check the version manifest hash before downloading', 'toggle_on'),
      gap(26),
      sec('DOWNLOADS', 'sources'),
      row('cloud-download', 'violet', 'Download source', '', 'value', 'Default mirror'),
      gap(26),
      sec('PERMISSIONS', 'android'),
      row('mic', 'rose', 'Microphone access',
          'Allow in-game voice chat to use the microphone', 'chevron'),
      gap(26),
      sec('DATA', 'migration'),
      row('database', 'amber', 'Run data migration',
          'Move the launcher data to the current storage layout', 'chevron'),
      gap(12),
      row('trash-2', 'rose', 'Clear metadata cache',
          'Remove cached mod and version metadata', 'chevron'),
      gap(12),
      row('memory-stick', 'cyan', 'Show memory warning',
          'Warn when the allocation is too high for this device', 'toggle_on'),
      gap(26),
      sec('FILES', 'external'),
      row('folder-open', 'mint', 'Open game directory', '', 'chevron'),
      gap(12),
      row('share-2', 'cyan', 'Share log file', '', 'chevron'),
      gap(12),
      row('package', 'amber', 'Execute a .jar', '', 'chevron'),
      gap(26),
      sec('STORAGE', '30.4 GB used'),
      { t: 'custom', id: 'storage', h: 210 },
    ],
  },
  // ------------------------------------------------------------------ 10
  {
    kicker: 'LABS', title: 'Experimental', subtitle: 'No support is provided for anything here',
    actions: [
      { icon: 'flask-conical', tint: 'violet', glow: true },
      { icon: 'rotate-ccw', tint: 'white' },
    ],
    blocks: [
      { t: 'note', icon: 'triangle-alert', tint: 'amber', h: 104,
        text: 'Experimental options can break rendering, audio or saves. Turn everything off before reporting a bug.' },
      gap(26),
      sec('GRAPHICS', '3 flags'),
      row('file-code', 'cyan', 'Dump shaders',
          'Write every shader the driver compiles to the log folder', 'toggle_off'),
      gap(12),
      row('cpu', 'amber', 'Force big core affinity',
          'Pin the game threads to the fastest cores', 'toggle_off'),
      gap(12),
      row('memory-stick', 'violet', 'Freedreno system memory',
          'Force the freedreno driver to allocate in system memory', 'toggle_off'),
      gap(26),
      sec('AUDIO AND BUFFERS', '2 flags'),
      row('audio-lines', 'mint', 'Force OpenSL in OpenAL Soft',
          'Use the OpenSL ES backend instead of AAudio', 'toggle_off'),
      gap(12),
      row('layers', 'rose', 'UBWC workaround',
          'Work around broken compressed framebuffer formats', 'toggle_off'),
      gap(26),
      sec('LOGGING', 'debug'),
      row('scroll-text', 'cyan', 'Live log view',
          'Show the game log overlay while playing', 'chevron'),
      gap(12),
      row('share-2', 'azure', 'Share log file', '', 'chevron'),
      gap(12),
      row('bug', 'rose', 'Verbose JNI logging',
          'Log every native call, slows the game down a lot', 'toggle_off'),
      gap(26),
      sec('DANGER ZONE', 'reset'),
      { t: 'custom', id: 'danger', h: 148 },
      gap(26),
      sec('ACTIVE EXPERIMENTS', 'session'),
      { t: 'custom', id: 'experiments', h: 200 },
    ],
  },
];
