"""Build icons.js (a Lucide sprite) for the interactive prototype.

Usage:  python3 tools/build_icons.py <lucide-static icons dir> <output.js>

The sprite keeps every icon as raw SVG inner markup so the prototype renders
with currentColor strokes and no external requests.
"""

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def inner(path):
    with open(path) as fh:
        svg = fh.read()
    m = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S)
    body = m.group(1) if m else ""
    body = re.sub(r"\s+", " ", body).strip()
    return body


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "/tmp/lucide/package/icons"
    out = sys.argv[2] if len(sys.argv) > 2 else "prototype/icons.js"
    names = json.load(open("/tmp/icon_names.json"))
    # status bar icons are drawn outside of the screen definitions
    names += ["signal", "wifi", "battery-full"]
    aliases = {"triangle-alert": "alert-triangle", "audio-lines": "audio-lines"}
    data, missing = {}, []
    for name in sorted(set(names)):
        path = os.path.join(src, f"{name}.svg")
        if not os.path.exists(path) and name in aliases:
            path = os.path.join(src, f"{aliases[name]}.svg")
        if not os.path.exists(path):
            missing.append(name)
            continue
        data[name] = inner(path)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as fh:
        fh.write("// Generated by tools/build_icons.py - Lucide icons, MIT licensed.\n")
        fh.write("export const ICONS = ")
        json.dump(data, fh, indent=0, sort_keys=True)
        fh.write(";\n")
    print(f"wrote {out}: {len(data)} icons")
    if missing:
        print("missing:", missing)


if __name__ == "__main__":
    main()
